# Generated by Django 5.1.6 on 2025-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
    ]
