# Generated by Django 5.1.6 on 2025-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_avatar_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expertUser',
            field=models.BooleanField(default=False),
        ),
    ]
