# Generated by Django 5.1.6 on 2025-02-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_expertuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expertUser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
